deploy:
  stage: deploy
  tags:
    - emr
  image: docker:cli
  script:
    - docker rm -f emr-backend emr-frontend 2>/dev/null || true
    - docker compose -p emr up -d --no-build
    # подождать, пока бек поднимется
    - sleep 10
    # миграции (с повтором на случай, если бек ещё не готов)
    - docker exec emr-backend alembic upgrade head
    - docker exec emr-backend python seed.py
  only:
    - master